version: '3.4'

services:
  clinicaltrialsapi:
    image: ${DOCKER_REGISTRY-}clinicaltrialsapi
    build:
      context: .
      dockerfile: ClinicalTrialsApi/Dockerfile
  clinicaltrialsdb:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - "54320:5432"
volumes:
  db:
    driver: local

    